# Рынок жилья

### В этот раз создадим датасет сами

### Шаг 1. Импортируем библиотеки

In [2]:
import pandas as pd

### Шаг 2. Сделаем 3 разных Series длины 100:
1. Случайные числа от 1 до 4
2. Случайные числа от 1 до 3
3. Случайные числа от 10 000 до 30 000

In [36]:
series_1 = pd.Series(range(1, 5)).sample(100, replace=True)
series_2 = pd.Series(range(1, 4)).sample(100, replace=True)
series_3 = pd.Series(range(10000, 30000)).sample(100, replace=True)

### Шаг 3. Сделаем датафрейм из этих колонок

In [21]:
df = pd.DataFrame({0: series_1.values, 1: series_2.values, 2: series_3.values})
df

    0  1      2
0   3  1  15467
1   2  1  20165
2   2  1  27816
3   4  3  18924
4   3  2  24854
.. .. ..    ...
95  4  3  27867
96  3  2  25461
97  2  2  16049
98  4  1  27436
99  2  3  21285

[100 rows x 3 columns]

### Шаг 4. Назовите колонки bedrs (комнаты), baths (ванные), price_sqr_meter (цена за метр)

In [18]:
df = df.rename(columns={0: 'bedrs', 1: 'baths', 2: 'price_sqr_meter'})

    bedrs  baths  price_sqr_meter
0       3      1            15467
1       2      1            20165
2       2      1            27816
3       4      3            18924
4       3      2            24854
..    ...    ...              ...
95      4      3            27867
96      3      2            25461
97      2      2            16049
98      4      1            27436
99      2      3            21285

[100 rows x 3 columns]

In [23]:
df.columns = ['bedrs', 'baths', 'price_sqr_meter']
df

    bedrs  baths  price_sqr_meter
0       3      1            15467
1       2      1            20165
2       2      1            27816
3       4      3            18924
4       3      2            24854
..    ...    ...              ...
95      4      3            27867
96      3      2            25461
97      2      2            16049
98      4      1            27436
99      2      3            21285

[100 rows x 3 columns]

### Шаг 5. Сделайте один длинный датафрейм bigcolumn из 3 Series с одной колонкой

In [37]:
bigcolumn = pd.DataFrame(pd.concat((series_1, series_2, series_3)))
bigcolumn

           0
3          4
3          4
3          4
0          1
1          2
...      ...
10984  20984
13885  23885
7706   17706
6566   16566
1989   11989

[300 rows x 1 columns]

### Шаг 6. Кажется, индекс идет только до 99. Проверим?

In [46]:
bigcolumn.index.max() < 100

False

### Шаг 7. Реиндексируйте датафрейм с 0 до 299

In [49]:
bigcolumn.reset_index(drop = True)

         0
0        4
1        4
2        4
3        1
4        2
..     ...
295  20984
296  23885
297  17706
298  16566
299  11989

[300 rows x 1 columns]